const $=id=>document.getElementById(id), n=id=>Number($(id).value)||0, p=id=>n(id)/100;
function init(){
 const cs=$('characterSelect');Object.entries(HSR_DATA.characters).forEach(([id,c])=>{const o=document.createElement('option');o.value=id;o.textContent=c.name;cs.appendChild(o)});
 const lc=$('lightConeSelect');Object.entries(HSR_DATA.lightCones).forEach(([id,c])=>{const o=document.createElement('option');o.value=id;o.textContent=c.name;lc.appendChild(o)});
 cs.addEventListener('change',loadCharacter);lc.addEventListener('change',calculate);loadCharacter();
 document.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',calculate));
 $('saveBtn').onclick=()=>{localStorage.setItem('hsrCalc',JSON.stringify(Object.fromEntries([...document.querySelectorAll('input,select')].map(x=>[x.id,x.type==='checkbox'?x.checked:x.value]))));alert('設定を保存しました');};
 $('loadBtn').onclick=()=>{const d=JSON.parse(localStorage.getItem('hsrCalc')||'null');if(!d)return alert('保存データがありません');Object.entries(d).forEach(([id,v])=>{if($(id))$(id).type==='checkbox'?$(id).checked=v:$(id).value=v});calculate();};
 $('resetBtn').onclick=()=>location.reload();
}
function loadCharacter(){const c=HSR_DATA.characters[$('characterSelect').value];$('charLevel').value=c.level;$('atk').value=c.atk;$('critRate').value=c.critRate;$('critDmg').value=c.critDmg;$('speed').value=c.speed;$('elementDmg').value=0;$('partyMain').textContent=c.name;$('resultCharacter').textContent=c.name;$('resultElement').textContent=c.element;const a=$('attackSelect');a.innerHTML='';Object.entries(c.attacks).forEach(([id,x])=>{const o=document.createElement('option');o.value=id;o.textContent=x.name;a.appendChild(o)});a.onchange=()=>{const x=c.attacks[a.value];$('multiplier').value=x.multiplier;calculate()};a.dispatchEvent(new Event('change'));}
function calculate(){const c=HSR_DATA.characters[$('characterSelect').value];if(!c)return;const atk=n('atk')*(1+p('buffAtk')+p('relicAtk'))+n('relicSet')*0;const base=atk*p('multiplier')+n('flatDamage');const cr=Math.min(1,p('critRate')+p('buffCrit'));let crit=1;if($('critMode').value==='crit')crit=1+p('critDmg')+p('buffCritDmg');else if($('critMode').value==='average')crit=1+cr*(p('critDmg')+p('buffCritDmg'));const dmg=1+p('elementDmg')+p('buffDmg');const effectiveDef=Math.max(0,n('enemyDef')*(1-p('defDown'))*(1-p('defIgnore')));const def=1-effectiveDef/(effectiveDef+10*n('enemyLevel')+200);const res=Math.max(0,1-p('resistance'));const taken=1+p('takenUp');const broken=Number($('broken').value);const final=base*crit*dmg*def*res*taken*broken;$('damage').textContent=Math.floor(final).toLocaleString('ja-JP');$('resultAttack').textContent=$('attackSelect').selectedOptions[0]?.textContent||'-';$('qCrit').textContent=crit.toFixed(4);$('qDmg').textContent=dmg.toFixed(4);$('qDef').textContent=def.toFixed(4);$('qRes').textContent=res.toFixed(4);const rows=[['基礎ダメージ',base],['会心係数',crit],['与ダメージ係数',dmg],['防御係数',def],['耐性係数',res],['被ダメージ係数',taken],['撃破係数',broken],['最終ダメージ',final]];$('breakdown').innerHTML=rows.map(([k,v])=>`<div><span>${k}</span><b>${v.toFixed(k.includes('係数')?4:2)}</b></div>`).join('');}
init();
